CREATE DATABASE SP_MEDICAL_GROUP;

USE SP_MEDICAL_GROUP;

CREATE TABLE TIPO_USUARIO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(200) NOT NULL UNIQUE
)

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR (255) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL
)

CREATE TABLE CLINICAS(
	ID INT IDENTITY PRIMARY KEY
	,NOME_FANTASIA VARCHAR (255) NOT NULL UNIQUE
	,ENDERECO VARCHAR(255) NOT NULL
	,HORA_FUNCIONAMENTO VARCHAR(255) NOT NULL
	,CNPJ CHAR(14) NOT NULL UNIQUE
	,RAZAO_SOCIAL VARCHAR(255) NOT NULL UNIQUE
)

CREATE TABLE ESPECIALIDADES(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
)

CREATE TABLE TIPO_SITUACAO(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
)

CREATE TABLE MEDICOS(
	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL UNIQUE
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICAS(ID) NOT NULL
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID) NOT NULL
	,CRM VARCHAR(100) NOT NULL UNIQUE
	,TELEFONE VARCHAR(50) NOT NULL
)

CREATE TABLE PRONTUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
	,TELEFONE VARCHAR(50)
	,ENDERECO VARCHAR(255)
	,DT_NASCIMENTO DATE NOT NULL
	,RG CHAR(9) NOT NULL UNIQUE
	,CPF CHAR(11) NOT NULL UNIQUE
)

CREATE TABLE CONSULTA(
	ID INT IDENTITY PRIMARY KEY
	,DATA_HOTA DATE NOT NULL
	,ID_PRONTUARIO INT FOREIGN KEY REFERENCES PRONTUARIOS(ID) NOT NULL
	,ID_MEDICO INT FOREIGN KEY REFERENCES MEDICOS(ID) NOT NULL
	,DESCRICAO TEXT
	,ID_TIPO_SITUACAO INT FOREIGN KEY REFERENCES TIPO_SITUACAO(ID) NOT NULL
)