USE SP_MEDICAL_GROUP

-------------------------

--USUARIO

SELECT
	U.NOME as Nome_do_usuario
	,U.EMAIL
	,TU.NOME as Tipo_do_usuario
FROM 
	USUARIOS U INNER JOIN TIPO_USUARIO TU
ON
	U.ID_TIPO_USUARIO = TU.ID

------------------------

--PRONTUARIO

SELECT
	U.NOME AS Nome_paciente
	,P.TELEFONE
	,P.ENDERECO
	,P.DT_NASCIMENTO as Data_Nascimento
	,P.RG
	,P.CPF
FROM
	PRONTUARIOS P 
INNER JOIN 
	USUARIOS U
ON
	P.ID_USUARIO = U.ID

--------------------------

--MEDICO

SELECT
	U.NOME
	,C.NOME_FANTASIA as clinica
	,E.NOME as especialidade
	,M.CRM
	,M.TELEFONE
FROM
	MEDICOS M JOIN CLINICAS C ON M.ID_CLINICA = C.ID

	JOIN USUARIOS U ON M.ID_USUARIO = U.ID

	JOIN ESPECIALIDADES E ON M.ID_ESPECIALIDADE = E.ID

---------------------------

--CLINICA

SELECT
	C.NOME_FANTASIA as Nome_Fantasia
	,C.ENDERECO as Endereco
	,C.HORA_FUNCIONAMENTO as Hora
	,C.CNPJ
	,C.RAZAO_SOCIAL
FROM
	CLINICAS C

---------------------------

--CONSULTAA

SELECT
	CONSULTA.DATA_HORA as Hora_da_consulta
	,PACIENTE.NOME AS Nome_Paciente
	,MEDICO.NOME AS Nome_Medico
	,MEDICOS.CRM AS Crm_Medico
	,CONSULTA.DESCRICAO
	,TIPO_SITUACAO.NOME AS Status_
	
FROM
	CONSULTA 
	JOIN TIPO_SITUACAO ON CONSULTA.ID_TIPO_SITUACAO = TIPO_SITUACAO.ID 
	JOIN PRONTUARIOS ON PRONTUARIOS.ID = CONSULTA.ID_PRONTUARIO
	JOIN USUARIOS PACIENTE ON PACIENTE.ID = PRONTUARIOS.ID_USUARIO
	JOIN MEDICOS ON MEDICOS.ID = CONSULTA.ID_MEDICO
	JOIN USUARIOS MEDICO ON MEDICO.ID = MEDICOS.ID_USUARIO

	


-----------

SELECT COUNT(*) FROM USUARIOS